# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5efc3da1400a41c11789b513
